# This is a basic workflow to help you get started with Actions

name: AuthTest

permissions:
  # This is required for requesting the JWT.
  id-token: write
  # This is required for actions/checkout.
  contents: read
  # This is reqruired for triggering workflows.
  actions: write

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: bydr-authtest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4


      - name: 'Azure login'
        id: azure_login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      - name: 'runvalidation'
        id: loginvalidation
        shell: pwsh
        run: |
            $Time = Get-Date
            $Runtime = (get-date).AddHours(3)

            Set-AzContext -Subscription "679f3d56-bed2-429f-9e31-4d7bf67e14c7"

            while ($currentTime -ne $Runtime) {
            try {

                Get-AzResourceGroup -Name "Alok_Maheshwari_RG" -ErrorAction Stop    
                $currentTime = $currentTime.AddMinutes(4)
                sleep 50    
                
            }
            catch {
                Write-Output "Activity Started at $($Time) and Exception Occurred at $($currentTime) following was the exception
                
                $_.Exception
                
                "
            }

            }#end



